# Allgemeine Informationen
application:
  name:             GDV-Xport-Services

logging:
  level:
    org:
      springframework:  INFO
      hibernate:        WARN
  url:  "jdbc:hsqldb:mem:logbook"

spring:
  mvc:
    favicon:
      enabled:      false
  profiles:
    active:         default

# Port 2517 ist 0x9D5 =~ gDV
server:
  port:             2517
